# Generated by Django 3.2.7 on 2021-10-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='User',
        ),
    ]
